/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package uk.gov.hmcts.ccd.bulk.user.management.app;

class MessageUtils {
    public static String getMessage() {
        return "Hello      World!";
    }
}
